In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
merged2 = pd.read_csv('datasets_consolidados/merged.csv') # Load merged log dataframe

In [3]:
merged2.drop(merged2.index[merged2['Severity'] == 'Normal'], inplace = True) # Remove alerts with Severity = Normal.

In [4]:
merged2

,Server,Severity,Date,Description,DateOnly,Average_min,Average_max,Average_mean,Average_median,Average_var,Average_std,Peak_min,Peak_max,Peak_mean,Peak_median,Peak_var,Peak_std
1,server01,Critical,2014-04-01 22:16:12,Power supply redundancy is lost.,2014-04-01,19,27,23.000000,23.0,32.000000,5.656854,30,30,30.000000,30.0,0.000000,0.000000
2,server01,Critical,2014-04-01 22:16:17,The power input for power supply 2 is lost.,2014-04-01,19,27,23.000000,23.0,32.000000,5.656854,30,30,30.000000,30.0,0.000000,0.000000
3,server01,Critical,2014-04-07 21:24:24,The power input for power supply 2 is lost.,2014-04-07,17,28,25.142857,26.0,10.728571,3.275450,20,35,31.714286,34.0,21.414286,4.627557
4,server01,Critical,2014-04-07 21:24:29,Power supply redundancy is lost.,2014-04-07,17,28,25.142857,26.0,10.728571,3.275450,20,35,31.714286,34.0,21.414286,4.627557
5,server01,Critical,2014-04-14 10:49:41,Power supply redundancy is lost.,2014-04-14,18,22,19.076923,19.0,1.576923,1.255756,20,26,22.076923,22.0,2.910256,1.705947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5956,server30,Critical,2019-05-06 17:22:32,The power input for power supply 1 is lost.,2019-05-06,20,20,20.000000,20.0,0.000000,0.000000,20,21,20.750000,21.0,0.204545,0.452267
5957,server30,Critical,2019-05-21 13:35:57,The power input for power supply 2 is lost.,2019-05-21,20,25,21.250000,21.0,1.152174,1.073394,22,26,22.666667,22.0,1.536232,1.239448
5958,server30,Critical,2019-05-21 13:35:57,Power supply redundancy is lost.,2019-05-21,20,25,21.250000,21.0,1.152174,1.073394,22,26,22.666667,22.0,1.536232,1.239448
5961,server30,Critical,2019-07-28 06:42:53,The power input for power supply 1 is lost.,2019-07-28,18,22,20.000000,20.0,1.200000,1.095445,20,30,22.312500,22.0,5.162500,2.272114
5962,server30,Critical,2019-07-28 06:42:56,Power supply redundancy is lost.,2019-07-28,18,22,20.000000,20.0,1.200000,1.095445,20,30,22.312500,22.0,5.162500,2.272114

In [5]:
merged2.to_csv(r'datasets_consolidados/merged2.csv', index = False)